version: "3.2"

services:
  redis:
    image: redis:alpine
    container_name: exess-cms-redis

  mysql:
    extends:
      file: docker/common-services.yaml
      service: mysql
    container_name: exess-cms-mysql
    ports:
      - "3316:3306"

  mysql-test:
    extends:
      file: docker/common-services.yaml
      service: mysql
    container_name: exess-cms-mysql-test
    ports:
      - "3416:3306"

  php:
    build: 
      context: docker/php
      args:
          - XDEBUG=1
    container_name: exess-cms-php
    working_dir: /exesscms-api
    volumes:
      - .:/exesscms-api
      - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
