parameters:
  exess.crud_records_path: '%kernel.project_dir%/Resources/Crud'

services:
  _defaults:
    autowire: true
    bind:
      $crudRecordsPath: '%exess.crud_records_path%'

  # General CRM commands
  ExEss\Bundle\CmsBundle\Command\AbstractAdminCommand:
    abstract: true
